import { getEnvVariable } from '../../../config';

export const WEEKLY_SUBSCRIPTION_PRICE_SOL = getEnvVariable("WEEKLY_SUBSCRIPTION_PRICE_SOL")
export const MONTHLY_SUBSCRIPTION_PRICE_SOL = getEnvVariable("MONTHLY_SUBSCRIPTION_PRICE_SOL")
export const LIFETIME_SUBSCRIPTION_PRICE_SOL = getEnvVariable("LIFETIME_SUBSCRIPTION_PRICE_SOL")